from collections.abc import Callable
from typing import Any

class BoolRef: ...
class ArithRef: ...
class CheckSatResult: ...
class ModelRef: ...

unsat: CheckSatResult

class Solver:
    def add(self, *args: BoolRef) -> None: ...
    def check(self) -> CheckSatResult: ...
    def model(self) -> ModelRef: ...

Ints: Callable[[str], Any]
And: Callable[..., BoolRef]
Or: Callable[..., BoolRef]
