"""Root Cause Left-Shift — RootCauseCategory Enum.

Traceable to: FR-007, FR-023
"""

from enum import StrEnum


class RootCauseCategory(StrEnum):
    """Categories for root cause analysis."""

    FORMAT_ERROR = "FORMAT_ERROR"
    COVERAGE_GAP = "COVERAGE_GAP"
    LLM_HALLUCINATION = "LLM_HALLUCINATION"
    PROCESS_GAP = "PROCESS_GAP"
    SEMANTIC_DRIFT = "SEMANTIC_DRIFT"
    NAMING_INCONSISTENCY = "NAMING_INCONSISTENCY"
    GOVERNANCE_BYPASS = "GOVERNANCE_BYPASS"
    SCAN_INCOMPLETENESS = "SCAN_INCOMPLETENESS"
    DECLARATION_IMPLEMENTATION_GAP = "DECLARATION_IMPLEMENTATION_GAP"
    NEW_CAPABILITY = "NEW_CAPABILITY"
    IMPROVEMENT = "IMPROVEMENT"
